### ISSUE TITLE
Improvement: documentation needed for DCparams

### ISSUE THREAD

**Issue by wjs20** [lightdock/lightdock-rust#11]
Hi! Thanks for this awesome set of tools :)

I was experimenting with the rust module for lightdock and I was curious as to what was inside the DCparams file in the data/ folder? 

Could you add an explanation of this folder somewhere in the docs?

**Comment by brianjimenez** [comment]
Thanks @wjs20 ! `DCparams` file comes directly from the DFIRE scoring function authors (the same parameters file can be found in the Python version of LightDock).

There is a Python script I added to the `trp_dummy` branch [here](https://github.com/lightdock/lightdock-rust/blob/trp_dummy/data/add_dummy_trp.py). The idea behind was basically adding a new dummy bead to the DFIRE scoring function using the tryptophan statistical potentials defined by DFIRE.

Hope it helps!
