### ISSUE TITLE
Cannot output docking score in version of 0.3.2

### ISSUE THREAD

**Issue by yrq3027** [lightdock/lightdock-rust#19]
Hi researchers! Nice job which help me a lot! When I run a docking in version of 0.3.2, there were nothing in these 3 files. If I change version of 0.2.0, it worked. Maybe, are there some change or bug in 0.3.2?
![034b73f29aae04c32bb708ded520490](https://github.com/user-attachments/assets/37bb1d68-8332-4413-905b-646dca2b9bf4)

**Comment by brianjimenez** [comment]
A few changes were made, if you execute the examples and tests do you experience the same issue?

**Comment by yrq3027** [comment]
Thank you for reply! I will try the examples later.

**Comment by brianjimenez** [comment]
Closing this ticket for the moment since there was no feedback provided. Please feel free to reopen.
