### ISSUE TITLE
Steps needed to add modified nucleic acids to the DNA scoring 

### ISSUE THREAD

**Issue by KasperBuskPedersen** [lightdock/lightdock-rust#20]
Dear lightdock developers

First of all, thank you for developing lightdock and lightdock-rust.

I'm a little new to lightdock. I want to add modified nucleic acids to the amber DNA scoring function (dna.rs) for lightdock-rust, for example deoxy-5-methylcytosine (dmc) (parameters here http://amber.manchester.ac.uk/), but I am unsure of the steps needed to do this and afraid I will miss something essential. 

Is it possible that you could list/walk me through the steps needed to add new bases/residues and make this work?

Best regards
Kasper

**Comment by brianjimenez** [comment]
Dear @KasperBuskPedersen , thank you for your kind words. You have already identified the correct file to modify (dna.rs). For a new modified nucleotide, you may need to add to the following dictionaries:

- [`VDW_CHARGES`](https://github.com/lightdock/lightdock-rust/blob/153298f2b161e3468a00db43188c16362c68cf97/src/dna.rs#L65C16-L65C27): if there is a new AMBER atom type in your modified nucleotide, add here its VDW charge from the AMBER FF.
 - [`VDW_RADII`](https://github.com/lightdock/lightdock-rust/blob/153298f2b161e3468a00db43188c16362c68cf97/src/dna.rs#L74): same for radius
 - [`AMBER_TYPES`](https://github.com/lightdock/lightdock-rust/blob/153298f2b161e3468a00db43188c16362c68cf97/src/dna.rs#L85): for every atom in the new type, add a new key`AMBER-TYPE-ATOM_NAME` and as value the mapping AMBER type.
 - Then add the electrostatics charges for every new pair added in the previous dictionary (https://github.com/lightdock/lightdock-rust/blob/153298f2b161e3468a00db43188c16362c68cf97/src/dna.rs#L146)
 - Same for N-terminal charges (https://github.com/lightdock/lightdock-rust/blob/153298f2b161e3468a00db43188c16362c68cf97/src/dna.rs#L207)

Finally, if AMBER notation is not following the PDB standard you might need to add a translation between PDB types and AMBER names here:
https://github.com/lightdock/lightdock-rust/blob/153298f2b161e3468a00db43188c16362c68cf97/src/dna.rs#L83

The rest of the code should act dinamically to the new types, so it is basically an exercise of adding new key-values in the specific dictionaries.

**Comment by KasperBuskPedersen** [comment]
@brianjimenez 

Thank you so much - and for the quick response! I will try this out.
