### ISSUE TITLE
Missing normal mode file when recreating example 1azp

### ISSUE THREAD

**Issue by KasperBuskPedersen** [lightdock/lightdock-rust#21]
Hi @brianjimenez 

I am trying to rerun the examples from the minimal setup of starting from only a protein and dna .pdb 
In the example folder of lightdock-rust/examples/1azp, there is the normal mode file needed to run called "rec_nm.npy"
However this file is not generated when running the python setup script "lightdock3_setup.py protein.pdb dna.pdb -anm -rst restraints.list". There is generated "lightdock_rec.nm.npy" though. How to generate "rec_nm.npy"

Best regards
Kasper

**Comment by JorgeRoel** [comment]
lgd_flatten.py lightdock_rec.nm.npy rec_nm.npy

**Comment by KasperBuskPedersen** [comment]
@JorgeRoel Thanks!
